FROM node:18-alpine

WORKDIR /usr/src

EXPOSE 7000

COPY ./package.json ./

RUN yarn

COPY . .

ENV SECRET_KEY=1g3,v;%-i=G<;
ENV DB_ID=root
ENV DB_PW=root
ENV DB_DATABASE=backup
ENV DB_PORT=3306
ENV DB_HOST=host.docker.internal
ENV ORIGIN=http://host.docker.internal:8000

RUN yarn build

CMD [ "yarn", "start:prod" ]
